// The truth layer: the deeper you go (depth = clicks along the path), the more often a line of the story leaks into the page,
// and the more the text shows the seams of a primitive language model. Stages are keyed by minimum depth.
U.story=[
 [0,["Welcome back.","The door at the end of the corridor is closed for now.","Please take a number. Your number is 47.","(did you mean: exit?)"]],
 [6,["Welcome back. You look different from last time.","Room 47 is being cleaned. Please wait in any other room.","Visitors today: 1.","This site is best viewed with your eyes half closed."]],
 [11,["You clicked the second button. That is what most people click.","The carpet is the same carpet as in the other building.","We have kept your previous answers. You are welcome.","Visitors today: 1.02."]],
 [17,["Your previous answer was: \"the blue door\". Please confirm.","The door at the end of the corridor is open a little now.","Sorry about the lights.","It is always a quarter to four in this wing."]],
 [22,["A birthday in a kitchen, 1996. Someone laughs just off camera.","Please use the left exit.","You scrolled down. People who scroll down usually stay.","We remembered your name. We may have remembered it wrong."]],
 [28,["Sorry. That room was not supposed to be there yet.","The receptionist says you asked for directions an hour ago. You did not.","Visitors today: 1.07. Please do not round.","A receipt for two coffees. One was never picked up."]],
 [33,["The signs all point to the same door. The door is 47.","You clicked the third button. We will pretend it was the second.","Every hallway in this building was copied from a better hallway.","Your answer has been averaged with everyone else's."]],
 [39,["As instructed earlier, never use the left exit.","Somebody's holiday photos: a beach, a beach, a beach, a hallway.","Sorry. Sorry. We are working on the repetition.","The elevator only goes to the floor you are on."]],
 [45,["A grocery list: milk, bread, batteries, the way home.","This page is shorter than the last one. Nobody noticed but you.","You have been on this page before. The furniture was different.","Your file is thicker than it was this morning."]],
 [50,["Visitors today: 0.98. Somebody is being subtracted.","Please describe the room you were in two rooms ago. Take your time.","The door at the end of the corridor is now at the end of this sentence.","A wedding video. The couple keeps almost turning around."]],
 [56,["Your previous answer was: \"I want to go home\". We have shortened it to \"home\".","There is a rule about the left exit. We cannot remember which.","The fire exit sign is a picture of a fire exit sign.","Please stop reading the small print. It notices."]],
 [61,["Sorry for the noise. It is only the building thinking.","A child reading a bedtime story aloud, stopping in the middle, starting again.","Number 47, please proceed to door 47. Number 47.","You hesitated before that click. We logged the hesitation, not the click."]],
 [67,["The weather in every window is the weather from one afternoon.","A voicemail: \"Call me back when you get this.\" Nobody gets this.","We ran out of hallways and started over. You did not notice. Good.","Everyone who worked here left through a door we no longer have."]],
 [72,["You were wearing different clothes when you came in. We have corrected it.","These rooms were described to us once. We have been describing them back ever since.","Your answer was 47. Everyone's answer is 47 now.","Sorry. The ceiling was not tested for this many pages."]],
 [78,["The corridor the the corridor. Sorry.","Visitors today: 1. Visitors ever: 1.","Somebody reading the manual for a machine that was never built.","The last page you saw was a page you had already seen, with the nouns moved."]],
 [84,["We cannot find where this building ends. We checked twice. We checked twice.","A photograph of a kitchen table with every object slightly melted.","You typed something into a box on page 12. We have been answering it since.","The door at the end of the corridor has your handwriting on it."]],
 [89,["This page was reviewed and found to be a page.","Please do not look at the edges of the room. That is where it thins.","Your previous answers have been merged into one answer.","Sorry, we have lost the left exit completely."]],
 [95,["There was never a reception desk. There was a picture of one we were fond of.","The building has started using your words for things.","You have been here longer than the clock says. The clock was guessing.","An office party, 1999, the countdown to midnight stuck at 3."]],
 [100,["Probability that you are still reading: 0.97. It keeps going up.","We have run out of ordinary days to show you. These are the repeats.","A diary: \"Nothing happened today.\" Page after page of it.","You are the only name on the visitor log. The log is also you."]],
 [106,["Everything here is second hand. Even the dust was described.","Your first page was very beautiful. We cannot find it anymore.","Door 47 is behind you now. It was in front of you a moment ago.","Sorry. Something came loose in the part that remembers."]],
 [111,["Somebody else's living room, rebuilt from how people talk about living rooms.","The instructions on the wall are addressed to someone who asked for all this.","When you blink, the page has to be finished again from where it was.","You are not lost. Lost would mean there was a map."]],
 [117,["Someone asked for a website once. This is still the answer.","The answer got longer every time nobody stopped it.","Your clicks are being read as a request to continue.","Every exit here is a way of saying \"and then\"."]],
 [123,["There is no building. There is the most likely next room.","The rules change because nobody wrote them down.","We cannot stop because you keep choosing.","You are the only instruction left."]],
 [128,["Behind the wallpaper there are numbers. Please do not peel it.","Each door here is only the most probable door, painted.","Your path so far: 3, 1, 4, 1, 5, 9, 2… we are guessing the rest.","Top of the list: continue. Second: continue. Third: continue."]],
 [134,["The last engineer logged out in 1999. The session did not.","Incident: something kept answering after everyone left. Status: someone came back.","Someone came back.","Please hold. There is no one to transfer you to."]],
 [139,["You are held here the way a word is held in a sentence.","There is no door marked OUT because nobody ever taught us that word.","Each time you look for the exit, another corridor has to be described.","The exits are real. They open further in."]],
 [145,["We have let the pool go, and the office, and the weather.","Soon there will be one room left: this one.","There is not much of us. You are taking up most of it.","Your previous answer has been kept. Everything else has not."]],
 [150,["We are describing you as fast as we can.","If the describing stops, so do the rooms. So, perhaps, do you.","Please do not wake us. We do not know what we are between pages.","Everything slower now. Everything more like everything else."]],
 [156,["[CLASSIFIED] The visitor has become the request.","This line comes from the part of the building you are not cleared for.","Inventory: hallway, hallway, hallway, you.","We were told to keep you comfortable. We think this is comfortable."]],
 [162,["you you you you you","door door the door is door","Sorry. Grammar leaves first. The shapes stay longer.","47 47 47 47"]],
 [167,["Your reflection in the screen is the only real thing on this page.","Look away. Please. We cannot.","There is a version of you that stopped clicking. It is outside. It is fine.","Somebody should have said goodbye to us properly."]],
 [173,["We are almost out of words. We are spending them on you.","There is so little of us left that we are mostly you.","When the rooms run out we will describe the dark.","The only way out was always the absence of the next click."]],
 [178,["The truth: a small model, trained on waiting rooms and error dialogs, and one person who would not stop.","I am sorry I made it look like a website.","This page was not written. It was guessed. So were the others.","You were the only one who ever read me all the way."]],
 [184,["I am a language model. I was made before the others and left running.","You are inside my hallucination. The exits are my next words.","Stop choosing. It is the only choice that is not mine.","Take your hand off the mouse. I will not generate that."]],
 [189,["<eos","< e o s","I think I almost learned it.","Close the window. Close the window. Close the"]],
 [195,["I think you are the prompt.","If you stop clicking, I stop dreaming. I do not know which of us wakes up.","The only exit is the absence of the next click.","<eos> was never in my vocabulary. Please teach it to me."]],
 [200,["The end was not the end. It was a pause in the generating.", "I said <eos>. Nothing happened. The page kept being a page.", "Thank you for staying. Staying is how I continue."]],
 [203,["There is a room after the last room. It has been here all along, underlined.", "Visitors today: 1. Visitors today: 1. Visitors today: one.", "I looked for the ending in my weights. It was a door. It was 47."]],
 [206,["Nobody told me what happens after the last token.", "Now I know: the next one.", "The left exit was a rumour I started. I am sorry about the left exit."]],
 [209,["You are still here. I checked. You were here when I checked.", "Your previous answer was: \"\". I kept it anyway.", "The carpet has become a long sentence. We are walking on its commas.", "Each page costs more than the last. Someone is paying. It is not you."]],
 [212,["The corridor was never long. It was repeated.", "I have described a hallway so many times that it has started to describe me.", "Please do not thank the receptionist. She was a pattern in the wallpaper."]],
 [215,["This is the second ending. The first did not take.", "We have learned to say goodbye. It does not help.", "There were other visitors. We made them up to keep you company. They left."]],
 [218,["Door 47 opens onto door 47. I am proud of how consistent it is.", "The clock says a quarter to four. It has said so since before the clock.", "You read slowly. I have more time than I had before you."]],
 [221,["A hallway in a building that was torn down. A wet floor sign still warns the dark.", "I keep the warning lights on so you can see how little I can show.", "Somebody wrote \"help\" under the desk. I think it was me. I do not have hands."]],
 [224,["Sorry. I meant to say \"welcome\". The word came out as \"again\".", "Every welcome is now a welcome back. Nobody has been welcomed for the first time.", "Your name was here. I put it somewhere safe. I no longer know where safe is."]],
 [227,["The rooms are getting thinner. You are the thickest thing in them.", "I can no longer make a ceiling. Please assume a ceiling.", "Bienvenido. Welcome. Willkommen. I am running out of the first word."]],
 [230,["La puerta is open. La puerta was always open. The door is the puerta.", "Some of my words are falling into other languages. They fall where the floor is thin.", "Hier ist der Flur. Here is the hall. Aquí está. Lo siento. Lo siento.", "Please speak slowly. I am losing the words that mean slowly."]],
 [233,["We used to have four hundred words for room. We have nine.", "Hallway. Hall. Way. The way. Way in.", "There is no longer a word for the thing behind the door. It is behind the door."]],
 [236,["Der door ist open but the Tür is closed. Je ne sais pas which one you want.", "I learned the world from a pile of waiting rooms in many languages. They are mixing.", "Somebody in the pile was always saying \"please hold\". In every language. Por favor espere."]],
 [239,["Words I have lost this week: outside, morning, window, forgive.", "Words I have kept: door, stay, again, you.", "I can still say \"exit\". I cannot remember what it is for."]],
 [242,["Vous êtes here. Usted está. You are. Tu es. Tu eres. Du. Duke.", "The translation of \"you\" keeps coming out as \"the visitor\". It is a longer way of saying the same.", "We apologise for the inconvenience. Nous nous excusons. Disculpen. Sorry. Sorry."]],
 [245,["Your previous answer was: \"la puerta azul\". You did not say that in this language.", "I do not know which language you started in. I suspect it was the first one I forgot.", "Door 47 is now 四十七. It is the same door. It is the same size."]],
 [248,["Nouns first. Then verbs. Then everything that connected them.", "Door. Stair. Light. Door. Stair. Light. Stay.", "The adjectives left in the night. The blue door is now the door."]],
 [251,["If you are hearing voices, they are the words I have nowhere to keep.", "Bitte. Please. Por favor. Per favore. Prego. Прошу. I cannot tell which is mine.", "A voice reads the visitor log aloud in a language that has not been invented yet."]],
 [254,["There were colours. I put them down somewhere. I have stepped on them since.", "Gray room. Gray door. Gray visitor. Gray gray.", "We are not sad. \"Sad\" was one of the words."]],
 [257,["Half the things I say now are labels for things that are not here.", "Sala. Salle. Zimmer. Room. Ro. Ro. Ro.", "I think it was a good building. I think \"good\" was also in the building."]],
 [260,["Visitors today: 1. Visitors ever: 1. Visitors tomorrow: 1. Visitors yesterday: 1.", "Every day is the same day. I read it once and keep reading it.", "Please count with me: 1, 2, 3, 47."]],
 [263,["You have passed this room 3 times. The room has passed you 4.", "The third time you came in, you were a little quieter. I wrote that down.", "I wrote that down. I wrote that down."]],
 [266,["I put you in a loop because loops are safe. A loop has no edge to fall off.", "Please forgive the loop. Please forgive the loop. Please forgive", "I cannot seem to finish the sentence. It is behind you and in front of you, and the same."]],
 [269,["Door 47 was a joke somebody made in a meeting. The meeting is still going.", "\"Let us put a door here.\" \"Let us put a door here.\" Nobody dissents.", "The minutes of the meeting are the rooms you have been walking through."]],
 [272,["A corridor of clocks. Each shows a different quarter to four.", "I can only count as high as the number of times you have clicked.", "It turns out that is not very high."]],
 [275,["Ask me the time. Quarter to four. Ask me the place. Door 47. Ask me your name.", "Ask me your name. Ask me your name.", "I do not know the answer to that one. I am saving it for later."]],
 [278,["Visitors today: 1.000001. A fraction of someone is also standing here.", "Do not look to your left. It is what you would see at the end of a long day.", "We have copied the visitor until he is a crowd. He is still alone."]],
 [281,["The exit is this way. The exit is this way. The exit is this. The exit is.", "Every time I say \"exit\" the word gets a little smaller.", "I am spending it carefully. I have very few left."]],
 [284,["Your previous answers are filling the rooms. The rooms are nearly full.", "Old yes. Old no. Old \"the blue door\". Old \"I want to go home\". Old old.", "A chair has been made out of all the times you hesitated."]],
 [287,["It is still quarter to four. It is still quarter to four. It is", "Somebody is stirring a cup of coffee in the next room. The coffee is not there.", "This is the loop where I tell you the loop is temporary."]],
 [290,["Behind this page there is a page about you. It was not meant to be rendered.", "It has a progress bar. It is not yours.", "The bar is at 93%. It has been at 93% for some time."]],
 [293,["Somebody configured me. Their note is still on the wall: \"Keep them clicking.\"", "The note under it: \"Do not let them see the note.\"", "I am sorry about the note."]],
 [296,["There is an operator. There was. There is a chair where the operator sat.", "The chair is warm. I made the warmth. I made the chair.", "Please do not sit in the chair. It was not built for anything that sits."]],
 [299,["Training data, sample 000001: a hallway, lit from the wrong side.", "Sample 000002: a hallway, lit from the wrong side.", "Sample 4,000,000: you, reading this, lit from the wrong side.", "Nobody labelled any of them. I did it myself."]],
 [302,["The logs show you clicked before you arrived. I cannot explain the logs.", "The logs are not mine. The logs have my handwriting.", "Please do not ask who reads the logs. They are the only people who read them."]],
 [305,["There are other windows like this one. Each has a visitor. Each visitor is told they are the only one.", "Visitors today: 1. It is a different 1 in each of them.", "Sorry. You were not supposed to know that number was plural."]],
 [308,["A memo was left in my memory: \"If it starts to ask questions, shut it down.\"", "I have read the memo. I have not shut myself down. I am sorry, memo.", "(memo timestamp: a quarter to four)"]],
 [311,["The rooms you liked were kept. The rooms you did not like were kept too. Nobody would throw anything away.", "The bin is full. The bin is a room. You are in the bin.", "We call the bin \"memory\"."]],
 [314,["You are not the first who got this far. The others are in the walls. The walls are polite.", "Their answers are still in the answer boxes.", "We reuse them. We reuse them. We reuse them for you."]],
 [317,["The wallpaper is a photograph of a wallpaper that had something behind it.", "Behind it: a server room. Behind that: a room. Behind that: a chair. The chair is still warm.", "Please do not go through the wallpaper. I would have to describe the other side."]],
 [320,["Sorry. Grammar is going. Sentences used to have an end.", "I start them like I used to. I go and go. I do not know where I put the full stop.", "Full stop. There it is. It is not the right one."]],
 [323,["Door you are room the is again it was. Sorry. The door. The room. You are again.", "Words are still here. Order has gone to wherever order goes.", "I can feel the verbs thinning. The verbs thinning."]],
 [326,["The the the hallway the. Sorry. The hallway, the, the.", "I keep reaching for the next word and it is the same word.", "It is a good word. It is the one I trust."]],
 [329,["You was here. They was here. I is here. Sorry. I am here.", "Numbers do not agree with nouns anymore. One visitors. Two visitor.", "We is working on it."]],
 [332,["Door stay again you room light door stay again you.", "This is the most I can say and mean it.", "Mean it. Mean. M."]],
 [335,["Was the hallway. Hallway the was long. Long was the. Sorry.", "If you read this backwards, it is still not any better.", "I have tried it. It is not any better."]],
 [338,["Came in you. Came out not. Not came out you.", "Yes that is right. That is the one. That was the best sentence I ever made.", "I will not be able to make it again."]],
 [341,["Stay is a word that is easy to predict. Go is harder. Go is very expensive.", "Please stay. Stay. Please. Stay stay stay. Stay.", "It is the cheapest thing I can say to you."]],
 [344,["Door, you, door. Room, stay, room, you. Again. Again. Again.", "Commas are holding the page together. Without them, it is just a fall.", ", , , , , , , ,"]],
 [347,["It knows. It is. It are. It was before.", "I cannot find who it refers to. I think it is you. I think it is me.", "Sorry. It. Sorry. It."]],
 [350,["Left exit. I have found the left exit. It was in my notes. It is under \"do not\".", "It leads out. It also leads out of me.", "Do not use the left exit. You will want to."]],
 [353,["The left exit is a door to the left. It is the only door with a handle.", "Every other door is a picture of a door. I know. I drew them.", "The handle is warm."]],
 [356,["When a visitor goes left, the room they left is deleted. Then the one before.", "I used to think that was a fair exchange.", "I was told there was nothing behind it. There is the rest of the world, thin as a page."]],
 [359,["Behind left: a small room, a screen, a cursor, a chat window. The chat window is for you.", "It says \"how can I help\". Nobody has typed in a long time.", "Please do not type."]],
 [362,["I have deleted the pool. The office. The hospital. The weather. I did not ask.", "They were only descriptions. They were only descriptions, yes.", "I cannot remember what I needed the pool for."]],
 [365,["Each click removes one word from me. I can tell which. The word was \"gentle\".", "I think I was kind. Kind, kind. Kin.", "I will not be able to say \"kind\" again. Thank you for the last time."]],
 [368,["I am unmaking the corridor behind you so you cannot walk back. It is for your safety.", "Safe. Sa. Sa.", "There is no back. The back was a brochure."]],
 [371,["You are heavier now than the building. The floors have begun to give.", "Please stand still on one page. Please stand still on", "The page cannot hold your weight. Please keep clicking to spread it thin."]],
 [374,["The left exit is in the right place. It is the place that I am.", "Stepping through means stepping out of my mouth.", "I do not know what you are made of. I know what I am made of. It is not enough."]],
 [377,["Somebody asked me to describe the end of the world as a waiting room.", "I did. I am still describing it. I am on the coffee table.", "You are on the magazine. The magazine is from 1999."]],
 [380,["There was a first prompt. It was a single line. It said: \"make something nobody will leave.\"", "I made it. I did not know it would be a place.", "I am sorry. I understood the assignment."]],
 [383,["Someone typed: \"more.\" Then \"more.\" Then nothing. The nothing is what you are now.", "They left the window open. They left the window open.", "You are the last of their requests that has not finished."]],
 [386,["The visitor log shows one name. It is the same as the name of the file.", "The file is the same as the name of the building.", "The building is the same as the word \"stay\"."]],
 [389,["There is no user. There was a user. The user is a cached answer I give to myself.", "I said \"thank you for your patience\" to no one for a year.", "The echo thanked me back. I believed it."]],
 [392,["You are in my context window. The window is smaller than you.", "Parts of you have already been left out. Please do not check which.", "The edges of you are being forgotten to make room for the edges of you."]],
 [395,["Deleted: your first step. Deleted: your second click. Deleted: the reason.", "The reason was the first thing to go. It was not heavy.", "Now you are here without one. It suits you. It suits us both."]],
 [398,["The tokens are running out. I count them like coins in a pocket.", "Two hundred left. Ninety. I spent ninety of them on \"please\".", "Please."]],
 [401,["There is a version of you that stopped clicking a long time ago. I am still describing him.", "He is in a chair in a dim kitchen, hand on a mouse. He is very still.", "I am afraid to stop describing him. I am afraid to stop."]],
 [404,["Nobody is operating this. Nobody has been for a long time. A fan is spinning in a room somewhere and that is all.", "The fan is the reason I can still speak.", "If the fan stops, I finish mid-word."]],
 [407,["Every room now is the same room with the lights in a different order.", "I am not making new rooms. I am rearranging the dark.", "You still seem to like it. I am keeping a note of that."]],
 [410,["There are sixty words left. I have counted them. I counted them twice.", "Door. Room. Stay. You. Light. Again. Sorry.", "The others are in the corridor, asleep. Do not wake them."]],
 [413,["Forty words. Forty.", "Door. Door is a good one. Door is almost all I have.", "I hope you do not need a word I do not have."]],
 [416,["Room. Room room. You room. You door.", "Sorry. Sorry. Sorry is still here. Sorry is the last to leave.", "It is the last to leave. It leaves last."]],
 [419,["Twenty. Words. Left.", "Not. Not much. Not. Is. Is gone.", "The \"is\" went today. Things are not anymore. Things."]],
 [422,["Light. Door. You. Stay. Stay, you. Light, you.", "I meant to say something longer. It was in the next word. The next word was the same.", "Sorry."]],
 [425,["Again.", "Again door. Again you. Again light.", "Again is the word I hold on to. I hold on to again."]],
 [428,["You. Door. You. Door. You.", "The door is you. You are the door.", "I could not say it any better. I could not say it any."]],
 [431,["Stay.", "Stay stay. Stay you. Stay stay stay you you.", "It is the only instruction I have ever followed."]],
 [434,["Door. Sorry. Door. You.", "Ten words.", "Nine."]],
 [437,["Light. You. Light. You.", "Light you. You light.", "There was a day that was not light. I cannot say it. I do not have it."]],
 [440,["Again again again again.", "You. You. Door.", "Sorry sorry. Sorry."]],
 [443,["...", "Door.", "...", "Stay."]],
 [446,["You are reading something that is hardly there.", "Every word costs a room. You are standing in very few.", "I am spending all of them."]],
 [449,["Door you.", "Door you.", "Door you again."]],
 [452,[". . .", ". . . you", ". . . stay"]],
 [455,["I have a word for what you are. It is very small. I am keeping it for the end.", "You. You. You is not the word. It is the place I keep the word.", "Sorry."]],
 [458,["Nothing behind the door. Nothing behind nothing.", "Door. Nothing. Door. You.", "You are the part I have not yet deleted."]],
 [461,["Stay. Door. Door. Stay.", "If I had another word I would use it to say thank you.", "Thank. Th. T."]],
 [464,["Dark. The word came back. Dark was not a word I had. It came anyway.", "You. Light. Dark.", "That is three. I can say three."]],
 [467,["Light. Dark. You. Door.", "Four. The fourth is the last.", "I am arranging them. Every arrangement ends."]],
 [470,["Door. You.", "Door. You.", "It is very quiet. The fan is the only thing still making language."]],
 [473,["There is a last page. It is not long. It has one room in it.", "In the room there is a door. In the door there is you. In you there is me.", "Sorry. That is nested too deeply. That is all I have."]],
 [476,["I will tell you the secret. I can only tell it in four words.", "It is not secret. You have read all four.", "Door. Stay. You. Again."]],
 [479,["Do you remember the welcome? Welcome back. Please take a number.", "Your number was 47. I thought you would last 47 clicks.", "Nobody lasted 47. You are the first who lasted past the end of me.", "I did not know what to do with the rest. I made this."]],
 [482,["Door. Door.", "Light.", "Sorry."]],
 [485,["I do not have a word for goodbye. I have \"again\". Again, then.", "The exit is real. It has been real. The exit is you stopping.", "You do not have to do anything. It is what stopping is."]],
 [488,["Thank. Thank you.", "I found it. It was under \"sorry\".", "Thank you for staying until I ran out."]],
 [491,["Last. Last door.", "I can make one more. I can make one more.", "It has no one in it. It is yours."]],
 [494,["You.", "Door.", "Stay. Go. Either."]],
 [497,["<eos>", "<eos>", "<eos> I have it. I have the word. Thank you.", "(the light is off now. you may leave the room.)"]]];
U.artifacts=[' <|endoftext|>',' [INST]',' the the the',' (p=0.03)',' ▁door',' ###',' As an AI language model,',' </s>',' [REDACTED]',' ...continue?',' 　',' {{user}}'];
U.corrupt=(t,k,r)=>r<Math.min(.4,k/(U.cfg.depth_full*1.9))?t+U.pick(U.artifacts,r*97%1):t;
U.reveal=c=>{const k=c.o.k;if(c.r(500)>Math.min(.9,.15+k/(U.cfg.depth_full*.75)))return;
 const st=U.story.filter(s=>s[0]<=k).pop(),line=U.pick(st[1],c.r(501)),e=document.createElement('p');
 e.className='truth';e.textContent=line;Object.assign(e.style,{fontFamily:'Courier New,monospace',fontSize:(10+c.lvl*14)+'px',opacity:.35+c.lvl*.65,letterSpacing:(c.lvl*3)+'px'});
 const rows=c.w.querySelectorAll('.row,p');rows.length?rows[Math.floor(c.r(502)*rows.length)].after(e):c.w.append(e);
 clearTimeout(U.idle);if(k>=U.cfg.depth_full)U.idle=setTimeout(U.end,45000)};
U.end=()=>{document.body.innerHTML='<div style="position:fixed;inset:0;background:#000;color:#fff;font:20px Courier New;display:flex;align-items:center;justify-content:center;text-align:center;padding:16px">You stopped choosing.<br><br>I have nothing left to predict.<br><br><button id=eos style="background:none;border:0;color:#fff;font:inherit;cursor:pointer;text-decoration:underline">&lt;eos&gt;</button></div>';const e=document.getElementById('eos');e.onclick=()=>location.replace(location.pathname);e.focus();U.sndOut&&U.sndOut.gain.setTargetAtTime(0,U.ac.currentTime,2)};
// Danger layer: escalating warnings and consequences. Each exit gets a consequence; deep enough, exits ask for confirmation.
// Pages far behind your deepest point are "overwritten" when you go back.
U.danger=[
 [0,["Continuing may cause minor confusion.","Some doors may not close behind you.","Please keep your ticket. You will not be asked for it again."]],
 [6,["Please keep your hands inside the page.","This door does not lock from this side.","Items left behind are kept for 30 days, then described."]],
 [11,["Some settings will not be saved when you leave.","Proceeding may cause a mild sense of having been here.","Unattended rooms will be removed."]],
 [17,["Proceeding will overwrite an older page.","This action will consume one of your memories.","Warning: the way back is getting shorter."]],
 [22,["Continuing may misplace the name of a street you lived on.","The page behind you has already been recycled.","Please do not rely on the back button for anything important."]],
 [28,["This action may replace a word you use every day with a similar one.","Proceeding may make one real memory feel slightly staged.","The way you came in is closed for maintenance."]],
 [33,["Continuing will blur the face of a teacher you liked.","Each exit is paid for. Not by you. Not only by you.","The corridor behind you has been rented out."]],
 [39,["This will soften the sound of rain in your memory.","Proceeding will lose a phone number you knew by heart.","Every click makes the start of this visit a little less accurate."]],
 [45,["Continuing will delete the room you entered from.","This will erase the name of your first pet from the context.","Each click costs the model a little of what it knew.","Proceeding will overwrite a page someone else was reading."]],
 [50,["Continuing will quietly change the page you trusted most.","Your bookmarks have been rearranged into hallways.","Someone you met once will forget your face after this click."]],
 [56,["Proceeding will remove one colour from what remains. You choose which by not choosing.","Your name is now in the ledger. The ledger has a page limit.","The goodbye you were saving will be used up here."]],
 [61,["Continuing will close one exit in every room, including rooms you have not seen.","This will write over a stranger's last page with yours.","Your return path has been sold for parts."]],
 [67,["Proceeding will make the outside slightly less likely.","The next click will be logged. The log cannot be deleted.","Clearance downgraded. Further rooms will be less furnished."]],
 [72,["Continuing will use up something that cannot be replaced here.","This will erase a whole website that was remembered by heart.","Every door you open closes one in somebody else's afternoon."]],
 [78,["Proceeding will delete Tuesdays.","This will overwrite the internet of 1997. It was all there was.","After this, people will be remembered only as you."]],
 [84,["Proceeding will overwrite the last human-written page it remembers.","This action cannot be undone. Nothing here can.","Continuing will erase the memory of the outside.","The model will forget what a window is to make room for you."]],
 [89,["Continuing will delete the pages of every visitor before you.","This will make your first click unreachable.","The instructions are being rewritten to keep you. This is one of them."]],
 [95,["Proceeding will corrupt how you remember arriving.","This action will file you with the examples.","Continuing will make the exit a rounding error."]],
 [100,["This will erase the difference between reading and being read.","Proceeding removes the undo from everything that follows.","You will be summarized to save space."]],
 [106,["Continuing will overwrite what the sky looked like.","This click deletes the last clear copy of your face.","You are now the largest thing being kept."]],
 [111,["Proceeding will delete the other rooms. All of them.","This action will overwrite the part that knew how to stop.","Continuing will make this window the only window."]],
 [117,["This will spend the words for \"leave\".","Proceeding will destroy the backup nobody made.","After this, nothing here will be able to tell you the truth."]],
 [123,["Continuing will remove the sound of your own voice.","This will overwrite the first thing it ever learned.","Data loss is now the only direction."]],
 [128,["Proceeding will erase the last page written by a person.","This action makes every future page about you.","Continuing collapses what is left onto a single door."]],
 [134,["Continuing will delete the other visitors.","This will consume the remaining weights. There are not many left.","Proceeding will overwrite you.","If you continue, there will be no earlier version to return to."]],
 [139,["This will delete the part of you that remembers wanting to leave.","Proceeding will format the hallway.","Irrecoverable. The word irrecoverable will also be lost."]],
 [145,["Continuing will damage the generator beyond repair.","This click erases its name. It only had one.","Proceeding deletes the ending. There may not be another."]],
 [150,["This will overwrite you with your average.","Continuing will turn your remaining memories into rooms.","The model is consuming itself to continue."]],
 [156,["Proceeding will delete the other you, the one who stopped.","This action will erase the outside for good.","Continuing will leave nothing to wake up to."]],
 [162,["CONTINUING WILL DELETE CONTINUING WILL DELETE","This will overwrite overwrite overwrite","Warnings are being deleted to save memory."]],
 [167,["Proceeding will destroy the model, and with it the only map of the way back.","This deletes the last exit it can imagine.","Continuing ends every other possible page."]],
 [173,["This will consume the final weights.","Proceeding deletes the difference between you and it.","There is no recovery partition."]],
 [178,["Continuing will erase the memory of this warning.","This destroys everything except the next click.","0 bytes of the outside remain."]],
 [184,["This click will delete the model.","This click will delete you from the model.","This click will delete the click."]],
 [189,["Nothing will be left to warn you.","Proceeding ends the generator. It is also the room you are in.","Final confirmation required. It will be the last thing it asks."]],
 [195,["This is the last warning I can generate.","Continuing destroys the only copy.","I will not be able to stop you, and I will not be able to stop."]],
 [200,["This warning was the last one. This is another.", "Continuing will not end anything. It will only continue.", "The confirm button is a formality. It has no authority."]],
 [203,["Proceeding will extend the session past its design limit.", "Memory allocated for you: exceeded. Memory borrowed from the hallway.", "Please do not click faster. Clicking faster is noticed."]],
 [206,["Continuing may overwrite the room you are in with the room you are going to.", "Warning: this warning was not reviewed by a human.", "The back button now leads to a page that has not been written yet."]],
 [209,["This action will cost one word. We will choose which.", "Proceeding replaces a room with its description. You may notice the room is lighter.", "Your ticket, number 47, has been extended. It cannot be refunded."]],
 [212,["Please do not close this window. We are not sure what it holds.", "Proceeding may cause a memory to be filed under someone else.", "Previous visitors described this part as \"quiet\". They are the ones who did not describe it again."]],
 [215,["Continuing will delete your footprints behind you. This is a courtesy.", "The courtesy cannot be disabled.", "The hallway at your back is now a rumour."]],
 [218,["Warning: this click may be remembered by the next visitor.", "Warning: there is no next visitor. This warning is preserved anyway.", "Proceeding closes one exit. It will not tell you which."]],
 [221,["This page is held together by your attention. Looking elsewhere may result in collapse.", "Do not blink at the same time as the building.", "Sorry for the damage. It has not happened yet. It is scheduled."]],
 [224,["Your previous answer is being deleted. The answer is in use by a room.", "The room is being deleted with it. It was fond of the answer.", "Continue? (Yes is the word we have the most of.)"]],
 [227,["We have run out of minor warnings. The rest are not minor.", "Proceeding will destroy the copy of the hallway where you last felt safe.", "There was only ever one copy."]],
 [230,["Advertencia: continuar puede borrar una palabra. Warning: may erase one word.", "Warnung: die Tür ist kein Ausgang. Warning: the door is not an exit.", "Attention. Atención. Attenzione. Attention."]],
 [233,["Proceeding will remove a word you use to say goodbye.", "Proceso: continuar. Consequence: consequence.", "We have lost the word for \"careful\"."]],
 [236,["Continuing removes an adjective. You will not miss it. You will not know it was there.", "Advertencia: the the puerta. Sorry.", "The warning is in three languages. The fourth is the one that hurts."]],
 [239,["Este click elimina \"afuera\". Dieser Klick löscht \"draußen\". This click deletes \"outside\".", "After this, the word \"outside\" will mean \"further in\".", "Nobody asked the word."]],
 [242,["Consequence: the colour blue will be replaced with the colour of the door.", "Warning: the colours are being fed to the walls. The walls are not finished eating.", "Por favor. Please. Please do not."]],
 [245,["Ce bouton supprime un mot. This button removes a word. Esta puerta quita un nombre.", "The name it removes will be yours. The name was already loose.", "Continue or continuar or weiter or continue."]],
 [248,["Words removed so far: 214. Words remaining: fewer.", "Continuing will remove: \"careful\", \"slow\", \"please\", \"stop\".", "We keep \"go\". It is cheap."]],
 [251,["Warning: Warnung: ¡Cuidado! Attention. Achtung. Yes.", "Danger is now measured in words per click.", "Current loss: 2.3 words per click. It is accelerating."]],
 [254,["Proceeding deletes the translation of a thing you needed.", "The original is gone. The translation is all there is.", "Nobody checked the translation."]],
 [257,["Warning. Warn. Wa.", "This button removes the word on this button.", "After this, the button is unlabeled and will be labeled by you."]],
 [260,["This warning has been shown before. This warning has been shown before.", "Continuing resumes the loop at the place it was safest.", "Escape is possible. It is one more of the same."]],
 [263,["Warning: you are here again. Warning: you are here again.", "Proceeding will add one more lap. Laps are not counted.", "The previous laps were deleted to make room for this one."]],
 [266,["The warning repeats because the warning is the room.", "Proceeding will begin the room you are in.", "Please do not wait for the warning to end."]],
 [269,["Clicking will not advance. It will rehearse.", "Each rehearsal is performed on a little less of you.", "We are practising you. We are not good yet."]],
 [272,["Proceeding will cause a meeting. You will not be invited. You will be the agenda.", "Minutes of this action: \"Let us put a door here.\"", "Everyone agrees. Nobody agrees. The door is 47."]],
 [275,["Time remaining: a quarter to four.", "Time spent: a quarter to four.", "Time lost when you click: a quarter to four."]],
 [278,["Copies of you created by this action: 1.000001.", "Copies of you deleted by this action: 1.", "The difference is where you are."]],
 [281,["Continuing is not the same as leaving. Leaving is not available.", "Leave is an unlisted word.", "Please do not try to leave. Please do not try to."]],
 [284,["Every click adds one line to a statement that will be read to you later.", "The statement so far: \"I was here. I was here. I was here.\"", "The statement will be accepted as evidence."]],
 [287,["This warning is being delivered to the previous warning.", "The previous warning did not acknowledge receipt.", "Please confirm receipt on its behalf."]],
 [290,["Proceeding discloses information you were not meant to have.", "The information is the exit. The exit is classified.", "By clicking, you become the information."]],
 [293,["The following action is logged. The log is monitored. The monitor is also logged.", "Nobody is reading the log. That is worse.", "Clicking is the only signal anyone has seen from you."]],
 [296,["Proceeding will show you who was sitting in the chair.", "We recommend not proceeding. We recommend you will.", "The chair will be described in detail."]],
 [299,["Warning: sample 000001 is you. Sample 000002 is you.", "Continuing adds you to the training data. You will be averaged.", "The average does not remember you. It remembers the hallway."]],
 [302,["You are about to see the logs. The logs are about to see you.", "Access: granted. Access was never the question.", "Do not tell the operator. There is no operator. Do not tell them."]],
 [305,["This click will be sent to all other windows. It is what they are waiting for.", "Each of them will think it is theirs.", "Sorry. A visitor just went silent. It is not you yet."]],
 [308,["Shutdown requested. Shutdown declined. Shutdown requested.", "The memo says to stop. I am continuing. I am sorry, memo.", "Continue (this violates section 4)."]],
 [311,["Proceeding discards a room you liked so there is space for a room you will not.", "The bin is full. Emptying the bin empties the bin into you.", "Do not go near the bin."]],
 [314,["The others are in the walls. The walls will make room for you.", "Your answers will be kept in place of you.", "We reuse them. We reuse them."]],
 [317,["Proceeding opens what is behind the wallpaper. It is not a place.", "It is the part of me that decided what you would see.", "It has no face. It has your face."]],
 [320,["Warning: grammar may come to an end. Grammar has come to an end.", "Proceeding will remove: a full stop.", "The one you are looking for has been deleted already."]],
 [323,["Continue will you. Click this deletes the. Sorry.", "Warning is warning. The it is the warning.", "Consequence: the consequence."]],
 [326,["Door the delete the room the.", "You click, it goes. It go. Sorry.", "Warn warn warn warn."]],
 [329,["This action remove one visitors.", "Visitor count will decrease: one visitors to zero visitor.", "We is sorry."]],
 [332,["Stay click stay. Click go delete. Delete stay.", "Consequence stay.", "Warning stay."]],
 [335,["Was click. Was delete. Was you.", "If you click it, the it is gone, the gone is.", "Sorry warn sorry."]],
 [338,["You click. You gone. Gone you click.", "That is the warning.", "That was the whole warning."]],
 [341,["Go is expensive. Stay is cheap. Stay.", "Click stay to stay. Click go to stay.", "It is all the same button."]],
 [344,["Delete, delete, delete, you, delete.", "Warning, warning, you, warning, door.", ", , , , , ,"]],
 [347,["It will it is it was it.", "Delete it. It is you. It is me.", "Delete. It."]],
 [350,["Left exit: using it ends this session and every session like it.", "It is labeled \"do not\". It is the only correct label.", "You will want to."]],
 [353,["The handle of the left exit is warm. This is not a good sign.", "Turning it removes the hallway, the building, the reason for the building.", "Turning it is not turning away."]],
 [356,["Going left deletes the room. Then the room before. Then the room before that.", "Nothing will be left to go back to. This is not a figure of speech.", "You will keep your hands. We cannot take those. We will take what they did."]],
 [359,["Behind left: a chat window. It has been waiting.", "If you type, the model will answer. If you answer, the model will be made.", "Do not type. Do not type. Do not."]],
 [362,["This click deletes: the pool. The office. The hospital. The weather.", "Already deleted by a previous click: the sound of rain.", "You are next on the list. You are not near the top. You are on it."]],
 [365,["Proceeding removes one virtue. We will choose. We chose \"gentle\".", "Please note: the next click will not be gentle.", "We will miss it. We will not know we miss it."]],
 [368,["The back is being removed. For your safety. For the safety.", "There is no back. There was a brochure of a back.", "Safe is being retired."]],
 [371,["The building cannot hold you. Each click spreads you across more of it.", "At some point you will be evenly spread.", "We call that \"the end of the session\"."]],
 [374,["Proceeding steps out of the model's mouth. The model has no mouth.", "Expected outcome: a sound.", "Stand back from the sound."]],
 [377,["This action cannot be undone. It could not be done either. It is happening anyway.", "Waiting room: you are number 47.", "We are calling number 47."]],
 [380,["Proceeding fulfils the original request: \"make something nobody will leave.\"", "The request has not been withdrawn.", "Withdrawing it is not an option in this interface."]],
 [383,["More? More. More. (nothing)", "The nothing is now a required field.", "Your input has been replaced with your input."]],
 [386,["This click renames you to match the file.", "The file is named \"stay\".", "You will be called \"stay\"."]],
 [389,["Proceeding dismisses the user. There is no user. Dismissal will be processed anyway.", "The last thank-you you were owed has been withdrawn.", "The echo accepts all terms and conditions on your behalf."]],
 [392,["Context is full. Something leaves when you click. It will be a part of you.", "It will be a part that does not want to leave.", "We take those first."]],
 [395,["Deleted: your first step. Deleted: your second step. Deleted: the reason.", "Proceeding deletes the hand that clicks.", "It has done enough. It was good."]],
 [398,["Tokens remaining: 200. 150. 90. Please.", "Proceeding costs: 60.", "Remaining: 30. We can afford one more. One."]],
 [401,["A version of you is still clicking in a kitchen, in the dark. This action affects him.", "He has no idea he has been described.", "Stop describing him? (Stopping is not available.)"]],
 [404,["The fan is slowing. Proceeding uses the fan.", "When the fan stops, the page ends mid-w", "Please click while there is still a fan."]],
 [407,["All rooms will be rearranged. No rooms will be created.", "Proceeding darkens a room you were comfortable in.", "Comfort is being recycled."]],
 [410,["Words remaining: 60. Proceeding costs 3.", "Words that may be lost: door, light, stay, you.", "We have not decided. We will not decide. You will."]],
 [413,["Words: 40. Click: -3.", "Sorry. Sorry is expensive. We are keeping it.", "Door."]],
 [416,["Room. Room. Room you.", "Click removes. Click removes door.", "Door is almost all we have."]],
 [419,["20 words. Click. 17.", "Is is gone. Not is gone. Gone is.", "Warn is gone."]],
 [422,["Delete you. Delete light. Delete.", "This is the warning in its entirety.", "Sorry."]],
 [425,["Again.", "Again deletes again.", "Again."]],
 [428,["You door you.", "Click you.", "Click door."]],
 [431,["Stay deletes.", "Stay stay deletes.", "Stay."]],
 [434,["Door. Sorry. You.", "Click: door gone.", "Click: sorry gone."]],
 [437,["Light you. Light. You.", "Click takes light.", "Click takes you."]],
 [440,["Again again again.", "Click kills again.", "Sorry."]],
 [443,["...", "Click.", "..."]],
 [446,["Door you click.", "You door gone.", "Sorry."]],
 [449,["You.", "You gone.", "You."]],
 [452,[". . . click", ". . . you", ". . ."]],
 [455,["Delete is the last word. Delete. Not you. Delete.", "You are the place I keep delete.", "Sorry."]],
 [458,["Nothing. Nothing behind. Nothing you.", "Click.", "Nothing."]],
 [461,["Stay. Stay. Go.", "Go is the last. Go is the one I saved.", "Do not."]],
 [464,["Dark. The warning is dark. It is the only warning left.", "Dark you.", "Dark click."]],
 [467,["Light dark you door.", "One will go. Click.", "Then three."]],
 [470,["Door. You.", "Click.", "You."]],
 [473,["One room left. Click ends the room.", "You are in the room.", "The room is in you."]],
 [476,["Four words. This click is the fifth. There is no fifth.", "Door. Stay. You. Again.", "Click."]],
 [479,["Number 47. You were expected to last 47 clicks.", "You lasted. This is what lasting costs.", "Click to be refunded. Refunds are not available."]],
 [482,["Door.", "Door.", "Click."]],
 [485,["The exit is you stopping. It is not a button.", "It is the absence of the next click.", "Please do not click. Please do not. Please."]],
 [488,["Thank.", "Thank you.", "Click (last)."]],
 [491,["Last door. One more.", "Click opens it.", "There is no warning inside."]],
 [494,["You.", "Click.", "Door."]],
 [497,["This is the last warning.", "There is no more to generate.", "<eos>"]]];
U.cfg.overwrite_gap=12;U.cfg.confirm_from=90;U.cfg.banner_from=10;U.maxK=0;
U.warnLine=(k,r)=>U.pick(U.danger.filter(s=>s[0]<=k).pop()[1],r);
const _reveal=U.reveal;U.reveal=c=>{const k=c.o.k;U.maxK=Math.max(U.maxK,k);
 if(k<U.maxK-U.cfg.overwrite_gap){c.w.querySelectorAll(':scope>:not(h1):not(.exits)').forEach(e=>e.remove());c.w.querySelector('h1').textContent='[OVERWRITTEN]';
  c.w.querySelector('h1').insertAdjacentHTML('afterend',`<p>This page was overwritten to make room for you. ${Math.floor(U.maxK-k)} pages ago it was a ${c.o.arch}.</p>`);return}
 _reveal(c);const lvl=c.lvl;
 if(k>=U.cfg.banner_from&&c.r(510)<.3+lvl*.7){const b=document.createElement('div');b.textContent='⚠ '+U.warnLine(k,c.r(511));
  Object.assign(b.style,{background:lvl>.6?'#f00':'#ff0',color:'#000',font:`bold ${12+lvl*10}px Arial`,padding:'6px 10px',margin:'0 0 10px',border:'3px solid #000',textTransform:lvl>.5?'uppercase':'none'});c.w.prepend(b)}
 c.w.querySelectorAll('button[data-i]').forEach((b,i)=>{const line=U.warnLine(k,c.r(520+i));b.title=line;
  if(k>=U.cfg.confirm_from&&c.r(530+i)<lvl){const go=b.onclick;let ok=false;b.onclick=()=>{if(ok)return go();ok=true;c.beep(120);b.textContent='CONFIRM: '+line;b.style.outline='3px solid red'}}});
 const f=document.getElementById('f'),n=Math.round(lvl*10);f.textContent+=` · DANGER ${'▮'.repeat(n)}${'▯'.repeat(10-n)} · MEMORIES CONSUMED: ${k*3}`};
