U.words({
B:['Continue','Cancel','OK','Not OK','Maybe','Proceed anyway','Go back forward','Accept all','Reject some','Retry failure','Ignore forever','Next ↩','Previous →','Yes (no)','Help me leave','Finish starting','Submit twice','Close to open','Remind me yesterday','I agree to disagree','Enter exit','Skip skipping','Undo nothing','Save as unsaved','Apply (do not apply)','Learn less','Open door','Wait here'],
L:['Name of your name','Password (visible)','Mother\'s maiden password','Favorite error code','Date of death (optional)','Email (postal)','How lost are you?','Room number you remember','Door preference','Confirm confirmation code','Hallway ID','Number of exits seen','Your previous self','Time you arrived (approx.)','Reason for being here'],
X:['Your session has expired before it started.','This page intentionally left blank is not blank.','The room you requested is also requesting you.','Please do not press any button. Press a button to continue.','Clicking here will take you here.','All fields are required. No fields are available.','You have been here 0 times before.','The exit has been moved to a more convenient location.','Hallway not found. Try another hallway.','Your changes have been changed.','This window will close when you open it.','Nothing is loading. Please keep waiting.','We noticed you noticed.','Thank you for your patience. Patience is not available.'],
F:['EXE','TXT','DOOR','BAK','???','TMP','LNK','OLD','ROOM','DAT'],
E:['🚪','🪑','🌫','⬛','🔲','🕳','💡','📺','🧸','☎️']});
U.words({
B:['Take a number','Use the left exit','Not the left exit','Keep my answers','Forget my answers','Knock','Wait by the door','Try door 47','Call reception','Hold the elevator','Sign in again','Open the other door','It was the blue door','Turn the lights back on','Report a missing room','Ask for directions','Start over (again)','Come back later','Stay a little longer','Read the small print'],
L:['Your number (it is 47)','Colour of the door you came in through','Your previous answer (pre-filled)','Name as you remember it','Name as we remember it','Floor you pressed','Last thing you ate','Street you grew up on (approx.)','Who told you about this page','How many doors have you counted','Time on the clock in the lobby','Hand you use for clicking','What the carpet smells like','Answer from page 12','Distance to the nearest window','Person waiting for you','Reason you did not leave','Your seat on the bus that day','Song playing when you arrived','Something you forgot to do'],
X:['Your previous answer has been kept for your convenience.','The door at the end of the corridor is still there. It moved closer while you read this.','Now serving number 47.','Please use the left exit. Please do not use the left exit.','Visitors today: 1.','The receptionist has stepped away. The receptionist has always stepped away.','Somebody left their coat on the chair. It is still warm.','This room was vacuumed recently, in lines that do not reach the walls.','The vending machine is out of everything except the number 47.','Your form has been pre-filled with someone else\'s handwriting.','You have been here before. You sat by the window. There was no window.','The lights in this wing are on a timer. The timer is on a timer.','The fire drill is scheduled for a date that already happened.','A radio in the next room is playing a song you almost know.','The clocks agree with each other and with nothing else.','Please wait here. Here has been updated.','The carpet pattern repeats every four steps. So do you.','We noticed you slowed down on the last page. That is fine. That is noted.','This page was last modified tomorrow.','There is a lamp on in an office nobody has a key to.','Please take a leaflet. All the leaflets are the same leaflet.','Your parking ticket has been validated for a building you are not in.','Hold music plays in the stairwell. Nobody is on hold.','A birthday cake in the break room, uncut, with no name on it.','The water cooler bubbles once every time you click.','Somebody wrote your name on the whiteboard and underlined it twice.','Lost: one afternoon. If found, please do not return it.','This hallway is 47 doors long in both directions.','Sorry, the previous page is being used by someone else.','An umbrella is drying in the lobby. It has not rained here.','The elevator says it is going up. You can feel it going sideways.','Please keep this page. You will need it on the way out.','There are footprints on the ceiling tiles, and they are yours.','The map in the lobby has a red dot. It says YOU ARE HERE. It always does.','Your answers have been checked. Some of them have been improved.','There is a chair facing the wall in every room. It is for you.','The phone at the front desk rings once and then waits.','It is the same Tuesday it was.','Please disregard the previous instruction. And this one.','Everything in this room is slightly too familiar, like a word said too many times.']});
